//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int administrador_id { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string estilo { get; set; }
        public int licenciatura_id { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Licenciatura Licenciatura { get; set; }
    }
}
