
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
    using System.Collections.Generic;
    
public partial class Envio_mail
{

    public int envio_id { get; set; }

    public int persona_id { get; set; }

    public System.DateTime envio_fecha_hora { get; set; }

    public string envio_tipo { get; set; }

    public string envio_email_destino { get; set; }

    public string envio_respuesta_clave { get; set; }

    public Nullable<System.DateTime> envio_respuesta_recibida { get; set; }



    public virtual Persona Persona { get; set; }

}

}
