

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class HabProfDBContainer : DbContext
{
    public HabProfDBContainer()
        : base("name=HabProfDBContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Persona> Personas { get; set; }

    public virtual DbSet<Tesina> Tesinas { get; set; }

    public virtual DbSet<Licenciatura> Licenciaturas { get; set; }

    public virtual DbSet<Estado_tesina> Estados_tesinas { get; set; }

    public virtual DbSet<Historial_estado> Historial_estados { get; set; }

    public virtual DbSet<Servidor_de_correo> Servidores { get; set; }

    public virtual DbSet<Envio_mail> Envio_mails { get; set; }

    public virtual DbSet<Juez> Jueces { get; set; }

    public virtual DbSet<Administrador> Administradores { get; set; }

    public virtual DbSet<Director> Directores { get; set; }

    public virtual DbSet<Tesista> Tesistas { get; set; }

}

}

