
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
    using System.Collections.Generic;
    
public partial class Historial_estado
{

    public int historial_tesina_id { get; set; }

    public int tesina_id { get; set; }

    public int estado_tesina_id { get; set; }

    public string historial_tesina_descripcion { get; set; }

    public System.DateTime historial_tesina_fecha { get; set; }



    public virtual Tesina Tesina { get; set; }

    public virtual Estado_tesina Estado { get; set; }

}

}
