
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
    using System.Collections.Generic;
    
public partial class Licenciatura
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Licenciatura()
    {

        this.Personas = new HashSet<Persona>();

    }


    public int licenciatura_id { get; set; }

    public string licenciatura_nombre { get; set; }

    public string licenciatura_descripcion { get; set; }

    public string licenciatura_email { get; set; }

    public string licenciatura_email_clave { get; set; }

    public int servidor_id { get; set; }



    public virtual Servidor_de_correo Servidor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Persona> Personas { get; set; }

}

}
