//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int PersonaId { get; set; }
        public string ApellidoyNombre { get; set; }
        public string Usuario { get; set; }
        public string Clave { get; set; }
        public string Estilo { get; set; }
        public Nullable<System.DateTime> FechaBaja { get; set; }
    }
}
