//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int persona_id { get; set; }
        public string persona_nomyap { get; set; }
        public string persona_dni { get; set; }
        public string persona_email { get; set; }
        public string persona_domicilio { get; set; }
        public string persona_telefono { get; set; }
        public int licenciatura_id { get; set; }
    
        public virtual Tesista Tesista { get; set; }
        public virtual Director Director { get; set; }
        public virtual Juez Juez { get; set; }
        public virtual Administrador Administrador { get; set; }
        public virtual Licenciatura Licenciatura { get; set; }
    }
}
