//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servidor_de_correo
    {
        public int servidor_id { get; set; }
        public string servidor_nombre { get; set; }
        public string servidor_smtp_host { get; set; }
        public short servidor_smtp_port { get; set; }
        public bool servidor_enable_ssl { get; set; }
    }
}
