//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servidor_de_correo
    {
        public int servidor_id { get; set; }
        public string nombre { get; set; }
        public string smtp_server { get; set; }
        public short smtp_port { get; set; }
        public bool enable_ssl { get; set; }
    }
}
