
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
    using System.Collections.Generic;
    
public partial class Tesista
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tesista()
    {

        this.Tesina = new HashSet<Tesina>();

    }


    public int tesista_id { get; set; }

    public string tesista_legajo { get; set; }

    public string tesista_sede { get; set; }

    public Nullable<System.DateTime> tesista_fecha_baja { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tesina> Tesina { get; set; }

    public virtual Persona Persona { get; set; }

}

}
