
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
    using System.Collections.Generic;
    
public partial class Tesina
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tesina()
    {

        this.Historial_estados = new HashSet<Historial_estado>();

        this.Jueces = new HashSet<Juez>();

    }


    public int tesina_id { get; set; }

    public int estado_tesis_id { get; set; }

    public string tesina_tema { get; set; }

    public string tesina_descripcion { get; set; }

    public string tesina_borrador { get; set; }

    public System.DateTime tesina_plan_fch_presentacion { get; set; }

    public short tesina_plan_duracion_meses { get; set; }

    public short tesina_plan_aviso_meses { get; set; }

    public Nullable<short> tesina_calificacion { get; set; }

    public Nullable<System.DateTime> tesina_fecha_cierre { get; set; }

    public Nullable<short> tesina_calificacion_director { get; set; }

    public int tesista_id { get; set; }

    public int director_id { get; set; }



    public virtual Estado_tesina Estado { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Historial_estado> Historial_estados { get; set; }

    public virtual Tesista Tesista { get; set; }

    public virtual Director Director { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Juez> Jueces { get; set; }

}

}
