//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Aplicativo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tesis()
        {
            this.Historial_estados = new HashSet<Historial_estado>();
        }
    
        public int tesis_id { get; set; }
        public int estado_tesis_id { get; set; }
        public string tesis_tema { get; set; }
        public string tesis_palabras_clave { get; set; }
        public string tesis_borrador { get; set; }
        public System.DateTime tesis_plan_fch_presentacion { get; set; }
        public short tesis_plan_duracion_meses { get; set; }
        public short tesis_plan_aviso_meses { get; set; }
    
        public virtual Tesista Tesista { get; set; }
        public virtual Estado_tesis Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historial_estado> Historial_estados { get; set; }
    }
}
