
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Aplicativo
{

using System;
    using System.Collections.Generic;
    
public partial class Tipo_mail
{

    public int tipo_mail_id { get; set; }

    public string tipo_mail_tipo { get; set; }

    public string tipo_mail_html { get; set; }

}

}
